name: Lint

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  lint:
    name: "shellcheck launcher"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azohra/shell-linter@latest
        with:
          path: "launcher"

